export enum ENUM_GROUP_STATUS_CODE_ERROR {
    GROUP_NOT_FOUND_ERROR = 6200,
    GROUP_GUARD_INVALID_ERROR = 6201,
    GROUP_ACTIVE_ERROR = 6203,
    GROUP_EXIST_ERROR = 6204,
    GROUP_USED_ERROR = 6205,
}
