export enum ENUM_AUTH_PERMISSIONS {
    USER_CREATE = 'USER_CREATE',
    USER_UPDATE = 'USER_UPDATE',
    USER_READ = 'USER_READ',
    USER_DELETE = 'USER_DELETE',
    USER_IMPORT = 'USER_IMPORT',

    ROLE_CREATE = 'ROLE_CREATE',
    ROLE_UPDATE = 'ROLE_UPDATE',
    ROLE_READ = 'ROLE_READ',
    ROLE_DELETE = 'ROLE_DELETE',

    PERMISSION_READ = 'PERMISSION_READ',
    PERMISSION_UPDATE = 'PERMISSION_UPDATE',

    SETTING_READ = 'SETTING_READ',
    SETTING_UPDATE = 'SETTING_UPDATE',

    GROUP_CREATE = 'GROUP_CREATE',
    GROUP_UPDATE = 'GROUP_UPDATE',
    GROUP_READ = 'GROUP_READ',
    GROUP_DELETE = 'GROUP_DELETE',


    APPLICATION_CREATE = "APPLICATION_CREATE",
    APPLICATION_UPDATE = "APPLICATION_UPDATE",
    APPLICATION_READ = "APPLICATION_READ",
    APPLICATION_DELETE = "APPLICATION_DELETE",
}
