export enum ENUM_APPLICATION_STATUS_CODE_ERROR {
    APPLICATION_IS_INACTIVE_ERROR = 6600,
    APPLICATION_NOT_FOUND_ERROR = 6601,
    APPLICATION_EXIST_ERROR = 6602,
    APPLICATION_ACTIVE_ERROR = 6603,
    APPLICATION_USED_ERROR = 6604,
}
